In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as stats
import sklearn as sklearn
from sklearn import linear_model



data = pd.read_csv('diabetes_binary_health_indicators_BRFSS2015.csv')

In [49]:
data['Obese'] = np.where(data['BMI'] >= 30, 1, 0)

data.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Obese
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0,1
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0,0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0,0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0,0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0,0

In [77]:
data.describe()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.139333,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,0.811420,0.056197,0.951053,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875
std,0.346294,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,0.391175,0.230302,0.215759,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [13]:
zero = (data == 0).sum()
zero

Diabetes_binary         218334
HighBP                  144851
HighChol                146089
CholCheck                 9470
BMI                          0
Smoker                  141257
Stroke                  243388
HeartDiseaseorAttack    229787
PhysActivity             61760
Fruits                   92782
Veggies                  47839
HvyAlcoholConsump       239424
AnyHealthcare            12417
NoDocbcCost             232326
GenHlth                      0
MentHlth                175680
PhysHlth                160052
DiffWalk                211005
Sex                     141974
Age                          0
Education                    0
Income                       0
Obese                   165829
dtype: int64

Next we must split the data into training and a test set. 80 % of the data will be randomly chosen to be in the training set, the rest of the data will be for the test set.

In [57]:
count=int(len(data)*0.8)
training=data.sample(count)
target=training['Obese']
training=training.drop(columns=['Obese'])
training=training.drop(columns=['BMI'])


training.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
50567,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,1.0,0.0,5.0,30.0,30.0,1.0,1.0,13.0,6.0,6.0
161439,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,2.0,1.0,1.0,11.0,6.0,4.0
198704,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,4.0,6.0
127185,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,5.0,8.0
28222,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,2.0,0.0,2.0,0.0,1.0,5.0,6.0,8.0

In [59]:
test=data.drop(training.index)
obese=test['Obese']
test=test.drop(columns=['Obese'])
test=test.drop(columns=['BMI'])


test.head()
print(obese)

0         1
5         0
7         0
17        0
23        0
         ..
253657    0
253659    1
253663    0
253664    0
253677    0
Name: Obese, Length: 50736, dtype: int32

In [60]:
lr=linear_model.LogisticRegression(max_iter=1000)
lr.fit(training,target)

LogisticRegression(max_iter=1000)

We will fit a logistic regression model fro the training set, using the Obese variable as the target

In [61]:
preds=lr.predict(test)
print(preds)

correctPred=(preds==obese)
res=correctPred.sum()/len(obese)
print(res)

[1 0 0 ... 0 0 0]
0.6937086092715232

The model has an accuracy of .69

In [67]:
help=stats.add_constant(training)
model=stats.OLS(target,help).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Obese   R-squared:                       0.115
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     1254.
Date:                Tue, 05 Nov 2024   Prob (F-statistic):               0.00
Time:                        22:40:23   Log-Likelihood:            -1.2485e+05
No. Observations:              202944   AIC:                         2.497e+05
Df Residuals:                  202922   BIC:                         2.500e+05
Df Model:                          21
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                    0.3692      0.010     38.169      0.000       0.350       0.388
Diabetes_binary          0.1708      0.003     55.013      0.000       0.165       0.177
HighBP                   0.1479      0.002     64.273      0.000       0.143       0.152
HighChol                 0.0283      0.002     12.963      0.000       0.024       0.033
CholCheck                0.0241      0.005      4.513      0.000       0.014       0.035
Smoker                  -0.0206      0.002     -9.838      0.000      -0.025      -0.016
Stroke                  -0.0719      0.005    -13.755      0.000      -0.082      -0.062
HeartDiseaseorAttack    -0.0348      0.004     -9.449      0.000      -0.042      -0.028
PhysActivity            -0.0709      0.002    -28.569      0.000      -0.076      -0.066
Fruits                  -0.0346      0.002    -15.895      0.000      -0.039      -0.030
Veggies                 -0.0050      0.003     -1.862      0.063      -0.010       0.000
HvyAlcoholConsump       -0.0710      0.004    -16.236      0.000      -0.080      -0.062
AnyHealthcare            0.0050      0.005      1.036      0.300      -0.004       0.014
NoDocbcCost              0.0096      0.004      2.509      0.012       0.002       0.017
GenHlth                  0.0587      0.001     46.895      0.000       0.056       0.061
MentHlth             -5.731e-05      0.000     -0.384      0.701      -0.000       0.000
PhysHlth                -0.0026      0.000    -18.097      0.000      -0.003      -0.002
DiffWalk                 0.1136      0.003     34.716      0.000       0.107       0.120
Sex                      0.0180      0.002      8.677      0.000       0.014       0.022
Age                     -0.0220      0.000    -58.577      0.000      -0.023      -0.021
Education               -0.0157      0.001    -13.510      0.000      -0.018      -0.013
Income                   0.0067      0.001     11.301      0.000       0.005       0.008
==============================================================================
Omnibus:                   158896.854   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            22370.349
Skew:                           0.560   Prob(JB):                         0.00
Kurtosis:                       1.821   Cond. No.                         143.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

This checks which variables are signficant to the model

P val over .05=
MentHlth
AnyHealthcare
Veggies

In [72]:
training2=training
training2=training2.drop(columns=['MentHlth'])
training2=training2.drop(columns=['AnyHealthcare'])
training2=training2.drop(columns=['Veggies'])

test2=test
test2=test2.drop(columns=['MentHlth'])
test2=test2.drop(columns=['AnyHealthcare'])
test2=test2.drop(columns=['Veggies'])

In [70]:
lr2=linear_model.LogisticRegression(max_iter=1000)
lr2.fit(training2,target)

LogisticRegression(max_iter=1000)

In [75]:
preds2=lr2.predict(test2)
print(preds2)

correctPred2=(preds2==obese)
res2=correctPred2.sum()/len(obese)
print(res2)

[1 0 0 ... 0 0 0]
0.6934523809523809

Reflection: We are currently on track with the project, and have met all of the milestones we have set for ourselves. This includes having created some useful visualizations of the data, having finished our first machine learning model. We also have begun creating more with the goal of improved accuracy